apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: contentmanagement
  name: contentmanagement
  namespace: kawa-foundation-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contentmanagement
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/contentmanagement-default: "true"
        io.kompose.service: contentmanagement
    spec:
      containers:
        - env:
            - name: AZURE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: content-config
                  key: AZURE_CONNECTION
          image: zanzibarinh/contentmanagement:{{.Values.version}}
          name: contentmanagement
          resources: {}
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contentmanagement-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contentmanagement
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
status: {}