apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: contentmanagement-prod
  name: contentmanagement-prod
  namespace: kawa-foundation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contentmanagement-prod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/contentmanagement-prod-default: "true"
        io.kompose.service: contentmanagement-prod
    spec:
      containers:
        - env:
            - name: AZURE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: content-config
                  key: AZURE_CONNECTION
          image: zanzibarinh/contentmanagement:latest
          name: contentmanagement-prod
          resources: {}
      restartPolicy: Always
status: {}
